name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ~1.23.4
      - run: go install go.uber.org/mock/mockgen@latest
      - run: go generate ./...
      - run: go test ./...
      - run: go vet ./...
      - uses: dominikh/staticcheck-action@v1
        with:
          install-go: false
